version: '3'
services:
    app:
        build: .
        command: yarn client:watch
        ports:
            - 3000:3000
        # environment: 
        #     MONGO_URL: mongodb
        #     PORT: 4000
        volumes:
            - ./:/src/
            - nodemodules:/src/node_modules

volumes:
    nodemodules: {}