version: '3'
services:
    app:
        build: .
        # command: yarn client:watch
        ports:
            - 80:3000
        # environment: 
        #     PORT: 4000
        volumes:
            - ./:/var/www/
            - nodemodules:/var/www/node_modules

volumes:
    nodemodules: {}