version: '3'
services:
    app:
        build: .
        command: yarn client:watch
        ports:
            - 3000:3000
        # environment: 
        #     PORT: 4000
        volumes:
            - ./:/opt/app/
            - nodemodules:/opt/app/node_modules

volumes:
    nodemodules: {}