version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    # environment:
    #     PORT: 4000
    volumes:
      - ./:/var/www/example/
      - nodemodules:/var/www/example/node_modules
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./:/var/www/example/
    ports:
      - "80:80"

volumes:
  nodemodules: {}
